### ISSUE TITLE
Why ML and not C?

### ISSUE THREAD

**Issue by rizary** [antoyo/tiger-rs#2]
Hi, I stumbled upon this repository when I search building compiler in rust topic.

My question is why you choose the ML title beside the C one since Rust is really close to C if I recall correctly.

**Comment by rizary** [comment]
@antoyo hi!

**Comment by antoyo** [comment]
Rust is closer to ML in my opinion and pattern matching is very useful for writing compilers.

**Comment by rizary** [comment]
Thank you for your clarification. 

Best.
